<div class="row">
    <div class="col-md-6"><div class="form-group"><label for="lead_name">Lead Name <span class="text-danger">*</span></label><input id="lead_name" name="lead_name" value="{{ old('lead_name', $lead->lead_name ?? '') }}" class="form-control @error('lead_name') is-invalid @enderror" required>@error('lead_name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
    <div class="col-md-6"><div class="form-group"><label for="phone">Phone <span class="text-danger">*</span></label><input id="phone" name="phone" value="{{ old('phone', $lead->phone ?? '') }}" class="form-control @error('phone') is-invalid @enderror" required>@error('phone')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
    <div class="col-md-6"><div class="form-group"><label for="email">Email</label><input type="email" id="email" name="email" value="{{ old('email', $lead->email ?? '') }}" class="form-control @error('email') is-invalid @enderror">@error('email')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
    <div class="col-md-6"><div class="form-group"><label for="interested_property">Interested Property</label><select id="interested_property" name="interested_property" class="form-select @error('interested_property') is-invalid @enderror"><option value="">Select Property</option>@foreach($properties as $property)<option value="{{ $property->id }}" @selected(old('interested_property', $lead->interested_property ?? '') == $property->id)>{{ $property->name }}</option>@endforeach</select>@error('interested_property')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
    <div class="col-md-6"><div class="form-group"><label for="assigned_agent">Assigned Agent</label><select id="assigned_agent" name="assigned_agent" class="form-select @error('assigned_agent') is-invalid @enderror"><option value="">Select Agent</option>@foreach($agents as $agent)<option value="{{ $agent->id }}" @selected(old('assigned_agent', $lead->assigned_agent ?? '') == $agent->id)>{{ $agent->name }}</option>@endforeach</select>@error('assigned_agent')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
    <div class="col-md-6"><div class="form-group"><label for="lead_source">Lead Source</label><input id="lead_source" name="lead_source" value="{{ old('lead_source', $lead->lead_source ?? '') }}" class="form-control @error('lead_source') is-invalid @enderror" placeholder="e.g. WhatsApp, Referral">@error('lead_source')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
    <div class="col-md-4"><div class="form-group"><label for="lead_status">Lead Status <span class="text-danger">*</span></label><input id="lead_status" name="lead_status" value="{{ old('lead_status', $lead->lead_status ?? 'New') }}" class="form-control @error('lead_status') is-invalid @enderror" required>@error('lead_status')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
    <div class="col-md-4"><div class="form-group"><label for="next_follow_up_date">Next Follow-up Date</label><input type="date" id="next_follow_up_date" name="next_follow_up_date" value="{{ old('next_follow_up_date', isset($lead) && $lead->next_follow_up_date ? $lead->next_follow_up_date->format('Y-m-d') : '') }}" class="form-control @error('next_follow_up_date') is-invalid @enderror">@error('next_follow_up_date')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
    <div class="col-md-4"><div class="form-group"><label for="follow_up_status">Follow-up Status <span class="text-danger">*</span></label><select id="follow_up_status" name="follow_up_status" class="form-select"><option @selected(old('follow_up_status', $lead->follow_up_status ?? 'Pending') === 'Pending')>Pending</option><option @selected(old('follow_up_status', $lead->follow_up_status ?? '') === 'Completed')>Completed</option><option @selected(old('follow_up_status', $lead->follow_up_status ?? '') === 'Not Required')>Not Required</option></select></div></div>
    <div class="col-md-12"><div class="form-group"><label for="reminder">Reminder</label><input id="reminder" name="reminder" value="{{ old('reminder', $lead->reminder ?? '') }}" class="form-control"></div></div>
    <div class="col-md-6"><div class="form-group"><label for="call_notes">Call Notes</label><textarea id="call_notes" name="call_notes" rows="4" class="form-control">{{ old('call_notes', $lead->call_notes ?? '') }}</textarea></div></div>
    <div class="col-md-6"><div class="form-group"><label for="general_notes">General Notes</label><textarea id="general_notes" name="general_notes" rows="4" class="form-control">{{ old('general_notes', $lead->general_notes ?? '') }}</textarea></div></div>
</div>
